## SINGULAR VALUE DECOMPOSITION

In [ ]:
# SINGULAR VALUE DECOMPOSITION CODE
from numpy import array                                                         # Importing Libraries
from scipy.linalg import svd                                                    # Importing Libraries
import numpy as np                                                              # Assigning NumPy the alias of np
Rows = int(input("Enter the number of rows:"))                                  # Getting input of row for dimesnion on given matrix
Col = int(input("Enter the number of columns:"))                                # Getting input of column for dimesnion on given matrix
print("Enter the entries in a single line (separated by space): ")
entries = list(map(int, input().split()))                                       # Command to split the entries and filling the rows first of each column
matrix = np.array(entries).reshape(Rows, Col)                                   # Reshaping and printing matrix for user friendly output
print("Input Matrix:")
print(matrix)
U, E, Vt = svd(matrix)                                                          # Using inbuild funtion (svd) to solve the matrix
Diag_E=np.diag(E)
print("Left Orthogonal Matrix(U):")
print(U)                                                                        # Output screen with results
print("Diagonal Matrix(E):")
print(Diag_E)
print("Right Orthogonal Matrix(Vt):")
print(Vt)

Enter the number of rows:2
Enter the number of columns:2
Enter the entries in a single line (separated by space): 
1 2 3 4
Input Matrix:
[[1 2]
 [3 4]]
Left Orthogonal Matrix(U):
[[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]
Diagonal Matrix(E):
[[5.4649857  0.        ]
 [0.         0.36596619]]
Right Orthogonal Matrix(Vt):
[[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]


## DYNAMIC MODE DECOMPOSITION

In [ ]:
# DYNAMIC MODE DECOMPOSITION CODE 
from numpy import array        # Importing Libraries
from scipy.linalg import svd   #libraries and functions importing
import numpy as np             #
import time                    #
#Now we will define a function named DMDsolver which will split up our given matrix X into two matrices X1 and X2
def DMDsolver(X_given,r,no_predictions):
  X1 = X_given[:, : -1] #splitting our given matrix into two matrices X1 and X2  
  X2 = X_given[:, 1 :]
  R, C = X.shape #R,C rows and columns no , shape function performs the task of finding no of rows and columns
  U, E, Vt = np.linalg.svd(X1, full_matrices = False) #Applying SVD on X1 as a first step of DMD algorithm
  """In the next step we obtain the matrix A_bar which is an second and important step in DMD algo, this matrix is obtained by multiplication 
  of the truncated  matrices"""
  A_bar = np.matmul((np.matmul(np.matmul(U[:, : r].conj().T,X2),Vt[: r, :].conj().T)),np.diag(np.reciprocal(E[: r])))
  '''In the following step we obtain the eigen decomposition of the matrix A_bar into two matrices Phi and Q representing eigen values 
  and eigen vectors matrices respectively'''
  Phi, Q = np.linalg.eig(A_bar) 
  '''The folllowing step we find Psi matrix in order to find A matrix '''
  Psi=np.matmul(np.matmul(np.matmul(X2,Vt[: r, :].conj().T),np.diag(np.reciprocal(E[: r]))),Q)
  #Here we go to the final step of finding our matrix A which is the root of DMD prediction
  A=np.matmul(np.matmul(Psi,np.diag(Phi)),np.linalg.pinv(Psi))
  '''In the following steps we will start constructing our predictions matrix C which contains the prediction columns and the number of that 
  columns will be equal to the number of predictions we want as given in argument "no_predictions" '''
  C = np.zeros((R, no_predictions)) #This step represents the construction of zero matrix R x no_predictions
  d=1 #iteration counter
  while (d<=no_predictions): #Loop for editing the columns of zero matrix C into the prediction columns
    C[:,d-1]=((np.linalg.matrix_power(A, d)) @ X2)[:,-1]
    d=d+1
  return C #returning predicted values matrix 
X = np.zeros((5, 200))
X[0,:] = np.arange(1,201) #np.arrange (start,stop,step) this is important when your require patterns in input
X[1,:] = np.arange(2,202) #input in the format of nested array
X[2,:] = np.arange(3,203)
X[3,:] = np.arange(4,204)
X[4,:] = np.arange(5,205)
start = time.time()
s=DMDsolver(X,2,6)
end = time.time()
print(X)
print(s)
v=%timeit DMDsolver(X,2,6)
print(f"Runtime of the program is {end - start}")
print(v)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:27: ComplexWarning: Casting complex values to real discards the imaginary part
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:27: ComplexWarning: Casting complex values to real discards the imaginary part


[[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.  14.
   15.  16.  17.  18.  19.  20.  21.  22.  23.  24.  25.  26.  27.  28.
   29.  30.  31.  32.  33.  34.  35.  36.  37.  38.  39.  40.  41.  42.
   43.  44.  45.  46.  47.  48.  49.  50.  51.  52.  53.  54.  55.  56.
   57.  58.  59.  60.  61.  62.  63.  64.  65.  66.  67.  68.  69.  70.
   71.  72.  73.  74.  75.  76.  77.  78.  79.  80.  81.  82.  83.  84.
   85.  86.  87.  88.  89.  90.  91.  92.  93.  94.  95.  96.  97.  98.
   99. 100. 101. 102. 103. 104. 105. 106. 107. 108. 109. 110. 111. 112.
  113. 114. 115. 116. 117. 118. 119. 120. 121. 122. 123. 124. 125. 126.
  127. 128. 129. 130. 131. 132. 133. 134. 135. 136. 137. 138. 139. 140.
  141. 142. 143. 144. 145. 146. 147. 148. 149. 150. 151. 152. 153. 154.
  155. 156. 157. 158. 159. 160. 161. 162. 163. 164. 165. 166. 167. 168.
  169. 170. 171. 172. 173. 174. 175. 176. 177. 178. 179. 180. 181. 182.
  183. 184. 185. 186. 187. 188. 189. 190. 191. 192. 193. 194. 19

In [ ]:
from numpy import array        # Importing Libraries
from scipy.linalg import svd   #libraries and functions importing
import numpy as np
import time
#Now we will define a function named DMDsolver which will split up our given matrix X into two matrices X1 and X2
def DMDsolver(X_given,no_predictions): #Function
  X1 = X_given[:, : -1] #splitting our given matrix into two matrices X1 and X2  
  X2 = X_given[:, 1 :] #X1 and X2 are the two important matrices in the dynamic mode decomposition code
  R, C = X.shape #R,C rows and columns no , shape function performs the task of finding no of rows and columns
  A=np.matmul(X2,np.linalg.pinv(X1))
  C = np.zeros((R, no_predictions)) #This step represents the construction of zero matrix R x no_predictions
  d=1 #iteration counter
  while (d<=no_predictions): #Loop for editing the columns of zero matrix C into the prediction columns
    C[:,d-1]=((np.linalg.matrix_power(A, d)) @ X2)[:,-1]
    d=d+1
  return C #returning predicted values matrix 
X = np.zeros((5, 200))
X[0,:] = np.arange(1,201) #np.arrange (start,stop,step) this is important when your require patterns in input
X[1,:] = np.arange(2,202) #input in the format of list 
X[2,:] = np.arange(3,203)
X[3,:] = np.arange(4,204)
X[4,:] = np.arange(5,205)
start = time.time() #we mark the start time of the program
s=DMDsolver(X,6)
end = time.time() #End time of the program is noted so that the final time can be printed down 
print(s)
v=%timeit DMDsolver(X,6) #here we have the function that displays the time required for the program to run 
print(f"Runtime of the program is {end - start}") #printing the time required for exceution of the program


[[201. 202. 203. 204. 205. 206.]
 [202. 203. 204. 205. 206. 207.]
 [203. 204. 205. 206. 207. 208.]
 [204. 205. 206. 207. 208. 209.]
 [205. 206. 207. 208. 209. 210.]]
1000 loops, best of 5: 184 µs per loop
Runtime of the program is 0.022383689880371094
